# Generated by Django 4.0.2 on 2022-02-03 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='onwer_name',
            field=models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='test_project.user'),
        ),
        migrations.AlterField(
            model_name='kittyandhedgehog',
            name='owner_name',
            field=models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='test_project.user'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='name',
            field=models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='test_project.kittyandhedgehog'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='owner_name',
            field=models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='test_project.user'),
        ),
    ]
