# Generated by Django 4.0.2 on 2022-02-03 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_project', '0002_alter_bet_onwer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_name',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
