# Generated by Django 4.0.2 on 2022-02-05 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_project', '0004_select_bet'),
    ]

    operations = [
        migrations.AddField(
            model_name='select_bet',
            name='which_lot',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='test_project.lot'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kittyandhedgehog',
            name='species',
            field=models.CharField(choices=[('cat', 'cat'), ('hedgehog', 'hedgehog')], default='Cat or Hedgehog?', max_length=100),
        ),
    ]
