# Generated by Django 4.0.2 on 2022-02-09 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_project', '0005_select_bet_which_lot_alter_kittyandhedgehog_species'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kittyandhedgehog',
            name='owner_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_project.user'),
        ),
    ]
