# Generated by Django 4.0.2 on 2022-02-09 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_project', '0006_alter_kittyandhedgehog_owner_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kittyandhedgehog',
            name='owner_name',
            field=models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='test_project.user'),
        ),
    ]
